site: Journal Jekyll Theme

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    ## permalink: /blog/:slug
    permalink: /blog/:year-:month-:day/:title/
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-time-to-read
  - liquid_pluralize
  - premonition
  - jekyll-seo-tag

paginate: 6
paginate_path: "/blog/page:num/"

disqus:
  shortname: "fusion94org"
