site: fusion94.org

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    ## permalink: /blog/:slug
    permalink: /blog/:year-:month-:day/:title/
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false  # add comments to all blog posts
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rougeS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-time-to-read
  - liquid_pluralize
  - premonition
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-tagging-related_posts
  
paginate: 5
paginate_path: "/blog/page:num/"

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

disqus: "fusion94org"

post:
  template: _post.txt
  extension: md
#page:
#  template: _page.txt
#  extension: md
editor: code
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: /var/www/fusion94.org/html
